import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

/**
 * JSDoc Documentation Tests for DaemonRunner
 *
 * These tests verify that the DaemonRunner class and its interfaces
 * have proper JSDoc documentation according to the acceptance criteria:
 *
 * - DaemonRunner class has JSDoc with @example
 * - Exported interfaces (DaemonRunnerOptions, DaemonMetrics, DaemonLogEntry) have descriptions
 * - Public methods (start, stop, getMetrics) have @param, @returns, and @example tags
 */
describe('DaemonRunner JSDoc Documentation', () => {
  let sourceCode: string;
  let sourceLines: string[];

  beforeAll(() => {
    // Read the runner.ts source file
    const runnerPath = path.join(__dirname, 'runner.ts');
    sourceCode = fs.readFileSync(runnerPath, 'utf-8');
    sourceLines = sourceCode.split('\n');
  });

  describe('Interface Documentation', () => {
    it('should have JSDoc documentation for DaemonRunnerOptions interface', () => {
      const interfaceMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export interface DaemonRunnerOptions/);
      expect(interfaceMatch).toBeTruthy();

      const jsDocBlock = interfaceMatch![0];
      expect(jsDocBlock).toContain('Configuration options for the DaemonRunner');
      expect(jsDocBlock).toContain('Defines all settings needed to initialize and run the APEX daemon');
      expect(jsDocBlock.length).toBeGreaterThan(100); // Ensure substantial documentation
    });

    it('should have JSDoc documentation for DaemonMetrics interface', () => {
      const interfaceMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export interface DaemonMetrics/);
      expect(interfaceMatch).toBeTruthy();

      const jsDocBlock = interfaceMatch![0];
      expect(jsDocBlock).toContain('Real-time metrics and status information for the DaemonRunner');
      expect(jsDocBlock).toContain('comprehensive statistics about daemon performance');
      expect(jsDocBlock.length).toBeGreaterThan(100); // Ensure substantial documentation
    });

    it('should have JSDoc documentation for DaemonLogEntry interface', () => {
      const interfaceMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export interface DaemonLogEntry/);
      expect(interfaceMatch).toBeTruthy();

      const jsDocBlock = interfaceMatch![0];
      expect(jsDocBlock).toContain('Structure for daemon log entries');
      expect(jsDocBlock).toContain('format of log messages generated by the DaemonRunner');
      expect(jsDocBlock.length).toBeGreaterThan(80); // Ensure substantial documentation
    });

    it('should document all properties of DaemonRunnerOptions interface', () => {
      // Find the interface definition
      const interfaceStart = sourceCode.indexOf('export interface DaemonRunnerOptions');
      const interfaceEnd = sourceCode.indexOf('}', interfaceStart);
      const interfaceBody = sourceCode.substring(interfaceStart, interfaceEnd);

      // Check that all properties have JSDoc comments
      const properties = [
        'projectPath',
        'pollIntervalMs',
        'maxConcurrentTasks',
        'logFile',
        'logToStdout',
        'logLevel',
        'config',
        'healthMonitor'
      ];

      properties.forEach(property => {
        expect(interfaceBody).toMatch(new RegExp(`\\/\\*\\*[\\s\\S]*?\\*\\/[\\s]*${property}[?:]`));
      });
    });

    it('should document all properties of DaemonMetrics interface', () => {
      // Find the interface definition
      const interfaceStart = sourceCode.indexOf('export interface DaemonMetrics');
      const interfaceEnd = sourceCode.indexOf('}', interfaceStart);
      const interfaceBody = sourceCode.substring(interfaceStart, interfaceEnd);

      // Check that key properties have JSDoc comments
      const properties = [
        'startedAt',
        'uptime',
        'tasksProcessed',
        'tasksSucceeded',
        'tasksFailed',
        'activeTaskCount',
        'isRunning',
        'isPaused'
      ];

      properties.forEach(property => {
        expect(interfaceBody).toMatch(new RegExp(`\\/\\*\\*[\\s\\S]*?\\*\\/[\\s]*${property}[?:]|${property}:.*\\/\\*\\*`));
      });
    });
  });

  describe('DaemonRunner Class Documentation', () => {
    it('should have comprehensive JSDoc documentation for the DaemonRunner class', () => {
      const classMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export class DaemonRunner/);
      expect(classMatch).toBeTruthy();

      const jsDocBlock = classMatch![0];

      // Check for required content
      expect(jsDocBlock).toContain('APEX Daemon Runner');
      expect(jsDocBlock).toContain('orchestrates continuous task processing');
      expect(jsDocBlock).toContain('Key features:');
      expect(jsDocBlock).toContain('@example');

      // Verify substantial documentation
      expect(jsDocBlock.length).toBeGreaterThan(500);
    });

    it('should have at least two @example blocks in DaemonRunner class documentation', () => {
      const classMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export class DaemonRunner/);
      expect(classMatch).toBeTruthy();

      const jsDocBlock = classMatch![0];
      const exampleMatches = jsDocBlock.match(/@example/g);
      expect(exampleMatches).toBeTruthy();
      expect(exampleMatches!.length).toBeGreaterThanOrEqual(2);
    });

    it('should show realistic usage examples in class documentation', () => {
      const classMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export class DaemonRunner/);
      expect(classMatch).toBeTruthy();

      const jsDocBlock = classMatch![0];

      // Check for realistic usage patterns
      expect(jsDocBlock).toContain('new DaemonRunner(');
      expect(jsDocBlock).toContain('await daemon.start()');
      expect(jsDocBlock).toContain('daemon.getMetrics()');
      expect(jsDocBlock).toContain('await daemon.stop()');
    });
  });

  describe('Public Method Documentation', () => {
    describe('start() method', () => {
      it('should have comprehensive JSDoc documentation', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*async start\(\): Promise<void>/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('Start the daemon runner');
        expect(jsDocBlock).toContain('@throws');
        expect(jsDocBlock).toContain('@returns');
        expect(jsDocBlock).toContain('@example');
        expect(jsDocBlock.length).toBeGreaterThan(300);
      });

      it('should document error conditions with @throws tag', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*async start\(\): Promise<void>/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('@throws {Error}');
        expect(jsDocBlock).toContain('already running');
        expect(jsDocBlock).toContain('initialization fails');
      });

      it('should include realistic usage examples', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*async start\(\): Promise<void>/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('const daemon = new DaemonRunner');
        expect(jsDocBlock).toContain('await daemon.start()');
        expect(jsDocBlock).toContain('try {');
        expect(jsDocBlock).toContain('} catch (error) {');
      });
    });

    describe('stop() method', () => {
      it('should have comprehensive JSDoc documentation', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*async stop\(\): Promise<void>/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('Stop the daemon gracefully');
        expect(jsDocBlock).toContain('@param');
        expect(jsDocBlock).toContain('@returns');
        expect(jsDocBlock).toContain('@example');
        expect(jsDocBlock.length).toBeGreaterThan(300);
      });

      it('should document the timeout parameter', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*async stop\(\): Promise<void>/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('@param');
        expect(jsDocBlock).toContain('timeout');
        expect(jsDocBlock).toContain('Maximum time to wait for tasks');
      });

      it('should include multiple usage examples', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*async stop\(\): Promise<void>/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        const exampleMatches = jsDocBlock.match(/@example/g);
        expect(exampleMatches).toBeTruthy();
        expect(exampleMatches!.length).toBeGreaterThanOrEqual(2);
      });
    });

    describe('getMetrics() method', () => {
      it('should have comprehensive JSDoc documentation', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*getMetrics\(\): DaemonMetrics/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('Get current daemon metrics');
        expect(jsDocBlock).toContain('@returns');
        expect(jsDocBlock).toContain('@example');
        expect(jsDocBlock.length).toBeGreaterThan(300);
      });

      it('should document the return value', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*getMetrics\(\): DaemonMetrics/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        expect(jsDocBlock).toContain('@returns');
        expect(jsDocBlock).toContain('Current daemon metrics');
        expect(jsDocBlock).toContain('uptime, task counts, and status');
      });

      it('should include multiple usage examples with different scenarios', () => {
        const methodMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*getMetrics\(\): DaemonMetrics/);
        expect(methodMatch).toBeTruthy();

        const jsDocBlock = methodMatch![0];
        const exampleMatches = jsDocBlock.match(/@example/g);
        expect(exampleMatches).toBeTruthy();
        expect(exampleMatches!.length).toBeGreaterThanOrEqual(2);

        // Check for different usage scenarios
        expect(jsDocBlock).toContain('metrics.isRunning');
        expect(jsDocBlock).toContain('metrics.uptime');
        expect(jsDocBlock).toContain('metrics.tasksProcessed');
      });
    });
  });

  describe('JSDoc Quality and Standards', () => {
    it('should use consistent JSDoc formatting throughout the file', () => {
      // Check for proper JSDoc comment structure
      const jsDocBlocks = sourceCode.match(/\/\*\*[\s\S]*?\*\//g);
      expect(jsDocBlocks).toBeTruthy();
      expect(jsDocBlocks!.length).toBeGreaterThan(10);

      // Check that all JSDoc blocks start and end properly
      jsDocBlocks!.forEach((block, index) => {
        expect(block).toMatch(/^\/\*\*/);
        expect(block).toMatch(/\*\/$/);
      });
    });

    it('should have meaningful descriptions for all documented items', () => {
      const jsDocBlocks = sourceCode.match(/\/\*\*[\s\S]*?\*\//g);
      expect(jsDocBlocks).toBeTruthy();

      // Filter out very short blocks (property comments can be brief)
      const substantialBlocks = jsDocBlocks!.filter(block => block.length > 50);

      substantialBlocks.forEach((block, index) => {
        // Each block should have substantial content
        expect(block.length).toBeGreaterThan(30);
        // Should not just be placeholder text
        expect(block).not.toContain('TODO');
        expect(block).not.toContain('FIXME');
      });
    });

    it('should use proper TypeScript types in @param and @returns tags', () => {
      const paramMatches = sourceCode.match(/@param[^@\n]*/g);
      const returnsMatches = sourceCode.match(/@returns[^@\n]*/g);

      if (paramMatches) {
        paramMatches.forEach(param => {
          // @param should include parameter name and description
          expect(param).toMatch(/@param\s+\w+/);
        });
      }

      if (returnsMatches) {
        returnsMatches.forEach(returns => {
          // @returns should include meaningful description
          expect(returns.length).toBeGreaterThan(20);
        });
      }
    });

    it('should have @example blocks with valid TypeScript syntax', () => {
      const exampleRegex = /@example[\s\S]*?```typescript([\s\S]*?)```/g;
      let match;
      const examples: string[] = [];

      while ((match = exampleRegex.exec(sourceCode)) !== null) {
        examples.push(match[1]);
      }

      expect(examples.length).toBeGreaterThan(0);

      examples.forEach((example, index) => {
        // Basic syntax checks
        expect(example).toContain('const');
        expect(example).toContain('DaemonRunner');
        expect(example.trim().length).toBeGreaterThan(50); // Substantial examples

        // Check for common TypeScript patterns
        const hasNewDaemonRunner = example.includes('new DaemonRunner(');
        const hasAwait = example.includes('await');
        const hasProperObjectLiteral = example.includes('{') && example.includes('}');

        expect(hasNewDaemonRunner || hasAwait || hasProperObjectLiteral).toBe(true);
      });
    });

    it('should provide comprehensive coverage of functionality in examples', () => {
      // Extract all example blocks
      const exampleRegex = /@example[\s\S]*?```typescript([\s\S]*?)```/g;
      let match;
      const allExamples = [];

      while ((match = exampleRegex.exec(sourceCode)) !== null) {
        allExamples.push(match[1]);
      }

      const combinedExamples = allExamples.join('\n');

      // Check that examples cover key functionality
      expect(combinedExamples).toContain('new DaemonRunner(');
      expect(combinedExamples).toContain('.start()');
      expect(combinedExamples).toContain('.stop()');
      expect(combinedExamples).toContain('.getMetrics()');
      expect(combinedExamples).toContain('projectPath:');

      // Check for error handling examples
      expect(combinedExamples).toContain('try');
      expect(combinedExamples).toContain('catch');
    });
  });

  describe('Documentation Completeness', () => {
    it('should document all public methods and interfaces', () => {
      // Get all export statements
      const exportMatches = sourceCode.match(/export\s+(class|interface|function|const)\s+([A-Za-z_$][A-Za-z0-9_$]*)/g);
      expect(exportMatches).toBeTruthy();

      const publicExports = exportMatches!.map(exp => {
        const match = exp.match(/export\s+(?:class|interface|function|const)\s+([A-Za-z_$][A-Za-z0-9_$]*)/);
        return match ? match[1] : null;
      }).filter(Boolean);

      // Check that each public export has JSDoc documentation
      publicExports.forEach(exportName => {
        if (exportName) {
          const docPattern = new RegExp(`\\/\\*\\*[\\s\\S]*?\\*\\/[\\s\\n]*export\\s+(?:class|interface|function|const)\\s+${exportName}`);
          expect(sourceCode).toMatch(docPattern);
        }
      });
    });

    it('should have consistent documentation depth across all interfaces', () => {
      const interfaces = ['DaemonRunnerOptions', 'DaemonMetrics', 'DaemonLogEntry'];

      interfaces.forEach(interfaceName => {
        const interfaceMatch = sourceCode.match(new RegExp(`\\/\\*\\*[\\s\\S]*?\\*\\/[\\s]*export interface ${interfaceName}`));
        expect(interfaceMatch).toBeTruthy();

        const jsDocBlock = interfaceMatch![0];
        // Each interface should have substantial documentation
        expect(jsDocBlock.length).toBeGreaterThan(80);
        // Should contain description of purpose
        expect(jsDocBlock.toLowerCase()).toMatch(/(?:configuration|metrics|log|entry|options|structure|information)/);
      });
    });

    it('should provide usage guidance in class-level documentation', () => {
      const classMatch = sourceCode.match(/\/\*\*[\s\S]*?\*\/[\s]*export class DaemonRunner/);
      expect(classMatch).toBeTruthy();

      const jsDocBlock = classMatch![0];

      // Should provide guidance on how to use the class
      expect(jsDocBlock).toContain('features:');
      expect(jsDocBlock).toContain('@example');

      // Should explain key concepts
      expect(jsDocBlock.toLowerCase()).toMatch(/(?:autonomous|orchestrat|task|execution|daemon)/);
    });
  });
});