import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { ApexOrchestrator } from '../packages/orchestrator/src/index.js';
import { join } from 'path';
import { mkdirSync, writeFileSync, rmSync, readFileSync } from 'fs';
import type { Task } from '../packages/core/src/types/task.js';

/**
 * Tests to verify PR description generation implementation is complete
 * as stated in ROADMAP.md v0.2.0 section
 */
describe('PR Description ROADMAP Verification Tests', () => {
  let testDir: string;
  let orchestrator: ApexOrchestrator;

  beforeAll(() => {
    testDir = join(process.cwd(), 'test-temp-roadmap-verification');
    mkdirSync(testDir, { recursive: true });

    // Create minimal package.json for testing
    writeFileSync(
      join(testDir, 'package.json'),
      JSON.stringify({ name: 'test-project', version: '1.0.0' }, null, 2)
    );

    // Create minimal apex.yaml
    writeFileSync(
      join(testDir, 'apex.yaml'),
      `project:
  name: "Test Project"
  version: "1.0.0"
git:
  defaultBranch: "main"
workflows:
  feature:
    description: "Feature development workflow"
  bugfix:
    description: "Bug fixing workflow"
  refactor:
    description: "Code refactoring workflow"`
    );

    orchestrator = new ApexOrchestrator({ projectPath: testDir });
  });

  beforeEach(async () => {
    await orchestrator.initialize();
  });

  afterAll(() => {
    try {
      rmSync(testDir, { recursive: true, force: true });
    } catch (error) {
      console.warn('Failed to clean up test directory:', error);
    }
  });

  describe('ROADMAP v0.2.0 PR Description Generation Completeness', () => {
    /**
     * Verify that ROADMAP.md claims are accurate:
     * - 🟢 PR description generation (line 97)
     */
    it('should verify ROADMAP.md contains correct status for PR description generation', () => {
      const roadmapContent = readFileSync(join(process.cwd(), 'ROADMAP.md'), 'utf-8');

      // Verify PR description generation is marked as complete in v0.2.0
      const v020Section = roadmapContent.split('## v0.2.0')[1]?.split('## v0.3.0')[0];
      expect(v020Section).toBeDefined();
      expect(v020Section).toContain('🟢 PR description generation');
    });

    it('should confirm generatePRTitle method exists and is functional', () => {
      const orch = orchestrator as unknown as {
        generatePRTitle: (task: Pick<Task, 'workflow' | 'description'>) => string;
      };

      // Verify method exists
      expect(orch.generatePRTitle).toBeDefined();
      expect(typeof orch.generatePRTitle).toBe('function');

      // Verify it produces expected output
      const result = orch.generatePRTitle({
        workflow: 'feature',
        description: 'Add new authentication system'
      });

      expect(result).toBe('feat: new authentication system');
    });

    it('should confirm generatePRBody method exists and is functional', () => {
      const orch = orchestrator as unknown as {
        generatePRBody: (task: Pick<Task, 'description' | 'acceptanceCriteria' | 'id' | 'workflow' | 'branchName' | 'usage'>) => string;
      };

      // Verify method exists
      expect(orch.generatePRBody).toBeDefined();
      expect(typeof orch.generatePRBody).toBe('function');

      // Verify it produces expected structured output
      const mockTask = {
        description: 'Implement user authentication',
        acceptanceCriteria: '- Users can log in\n- Sessions are secure',
        id: 'task_auth_123',
        workflow: 'feature',
        branchName: 'apex/auth-feature',
        usage: { totalTokens: 2500, estimatedCost: 0.025 }
      };

      const result = orch.generatePRBody(mockTask);

      // Verify all expected sections are present
      expect(result).toContain('## Summary');
      expect(result).toContain('## Acceptance Criteria');
      expect(result).toContain('## Task Details');
      expect(result).toContain('**Task ID:** `task_auth_123`');
      expect(result).toContain('**Workflow:** feature');
      expect(result).toContain('**Branch:** `apex/auth-feature`');
      expect(result).toContain('**Tokens Used:** 2,500');
      expect(result).toContain('**Estimated Cost:** $0.0250');
      expect(result).toContain('🤖 Generated by [APEX]');
      expect(result).toContain('Users can log in');
      expect(result).toContain('Sessions are secure');
    });

    it('should verify PR description functionality is integrated with createPR method', async () => {
      // Create a mock task to test PR generation integration
      const task = await orchestrator.createTask({
        description: 'Add user dashboard',
        workflow: 'feature',
        acceptanceCriteria: '- Dashboard shows user stats\n- Real-time updates'
      });

      // Verify task was created successfully
      expect(task).toBeDefined();
      expect(task.id).toBeDefined();
      expect(task.workflow).toBe('feature');

      // Verify that the task has the properties needed for PR generation
      expect(task.description).toBe('Add user dashboard');
      expect(task.acceptanceCriteria).toBe('- Dashboard shows user stats\n- Real-time updates');
      expect(task.branchName).toBeDefined();
      expect(task.usage).toBeDefined();
    });

    it('should verify all workflow types have proper commit prefix mapping', () => {
      const orch = orchestrator as unknown as {
        generatePRTitle: (task: Pick<Task, 'workflow' | 'description'>) => string;
      };

      // Test all supported workflow types mentioned in ROADMAP
      const workflowTests = [
        { workflow: 'feature', expectedPrefix: 'feat:' },
        { workflow: 'bugfix', expectedPrefix: 'fix:' },
        { workflow: 'refactor', expectedPrefix: 'refactor:' },
        { workflow: 'docs', expectedPrefix: 'docs:' },
        { workflow: 'test', expectedPrefix: 'test:' },
        { workflow: 'unknown_workflow', expectedPrefix: 'feat:' } // fallback
      ];

      for (const test of workflowTests) {
        const result = orch.generatePRTitle({
          workflow: test.workflow,
          description: `${test.workflow} implementation`
        });

        expect(result).toMatch(new RegExp(`^${test.expectedPrefix.replace(':', '\\:')}`));
      }
    });

    it('should verify description cleaning functionality works correctly', () => {
      const orch = orchestrator as unknown as {
        generatePRTitle: (task: Pick<Task, 'workflow' | 'description'>) => string;
      };

      // Test various description cleaning scenarios as mentioned in ROADMAP
      const cleaningTests = [
        {
          input: 'Add user authentication system',
          expected: 'feat: user authentication system'
        },
        {
          input: 'Fix memory leak in cache',
          expected: 'feat: memory leak in cache'
        },
        {
          input: 'Update documentation',
          expected: 'feat: documentation'
        },
        {
          input: 'Implement caching layer',
          expected: 'feat: caching layer'
        },
        {
          input: 'Create new API endpoints',
          expected: 'feat: new api endpoints'
        }
      ];

      for (const test of cleaningTests) {
        const result = orch.generatePRTitle({
          workflow: 'feature',
          description: test.input
        });

        expect(result).toBe(test.expected);
      }
    });

    it('should verify PR body includes all required metadata as per ROADMAP claims', () => {
      const orch = orchestrator as unknown as {
        generatePRBody: (task: Pick<Task, 'description' | 'acceptanceCriteria' | 'id' | 'workflow' | 'branchName' | 'usage'>) => string;
      };

      const complexTask = {
        description: 'Implement comprehensive user management system with role-based access control',
        acceptanceCriteria: '- Admin can create/edit/delete users\n- Role-based permissions work correctly\n- Audit trail is maintained\n- Email notifications are sent',
        id: 'task_user_mgmt_456',
        workflow: 'feature',
        branchName: 'apex/user-management-rbac',
        usage: { totalTokens: 12500, estimatedCost: 0.125 }
      };

      const result = orch.generatePRBody(complexTask);

      // Verify all required metadata is included as claimed in ROADMAP
      const requiredElements = [
        '## Summary',
        '## Acceptance Criteria',
        '## Task Details',
        '**Task ID:** `task_user_mgmt_456`',
        '**Workflow:** feature',
        '**Branch:** `apex/user-management-rbac`',
        '**Tokens Used:** 12,500',
        '**Estimated Cost:** $0.1250',
        'Admin can create/edit/delete users',
        'Role-based permissions work correctly',
        'Audit trail is maintained',
        'Email notifications are sent',
        '🤖 Generated by [APEX]',
        'Autonomous Product Engineering eXecutor'
      ];

      for (const element of requiredElements) {
        expect(result).toContain(element);
      }

      // Verify proper markdown structure
      expect(result).toMatch(/## Summary\n\n/);
      expect(result).toMatch(/## Acceptance Criteria\n\n/);
      expect(result).toMatch(/## Task Details\n\n/);
    });

    it('should verify edge case handling matches ROADMAP promises', () => {
      const orch = orchestrator as unknown as {
        generatePRTitle: (task: Pick<Task, 'workflow' | 'description'>) => string;
        generatePRBody: (task: Pick<Task, 'description' | 'acceptanceCriteria' | 'id' | 'workflow' | 'branchName' | 'usage'>) => string;
      };

      // Test title truncation (ROADMAP claims proper handling)
      const longDescription = 'A'.repeat(100);
      const titleResult = orch.generatePRTitle({
        workflow: 'feature',
        description: longDescription
      });
      expect(titleResult.length).toBeLessThanOrEqual(66); // "feat: " + 60 chars

      // Test body with missing acceptance criteria
      const taskWithoutCriteria = {
        description: 'Simple task',
        id: 'task_simple',
        workflow: 'feature',
        branchName: 'apex/simple',
        usage: { totalTokens: 100, estimatedCost: 0.001 }
      };

      const bodyResult = orch.generatePRBody(taskWithoutCriteria);
      expect(bodyResult).toContain('## Summary');
      expect(bodyResult).toContain('## Task Details');
      expect(bodyResult).not.toContain('## Acceptance Criteria');

      // Test with zero usage values
      const zeroUsageTask = {
        description: 'Zero usage task',
        id: 'task_zero',
        workflow: 'test',
        branchName: 'apex/zero-usage',
        usage: { totalTokens: 0, estimatedCost: 0 }
      };

      const zeroUsageResult = orch.generatePRBody(zeroUsageTask);
      expect(zeroUsageResult).toContain('**Tokens Used:** 0');
      expect(zeroUsageResult).toContain('**Estimated Cost:** $0.0000');
    });
  });

  describe('Integration with Git Workflow (ROADMAP Verification)', () => {
    it('should verify git integration claims in ROADMAP are accurate', () => {
      // Verify that the orchestrator has the createPullRequest method as mentioned in ROADMAP
      expect(orchestrator.createPullRequest).toBeDefined();
      expect(typeof orchestrator.createPullRequest).toBe('function');
    });

    it('should verify automatic PR creation functionality exists', () => {
      const roadmapContent = readFileSync(join(process.cwd(), 'ROADMAP.md'), 'utf-8');

      // Verify ROADMAP claims about automatic PR creation
      expect(roadmapContent).toContain('🟢 Automatic PR creation via `gh` CLI');
      expect(roadmapContent).toContain('🟢 PR description generation');

      // Verify the functionality exists in the codebase
      expect(orchestrator.createPullRequest).toBeDefined();
    });
  });

  describe('Quality Assurance of ROADMAP Claims', () => {
    it('should verify all PR description features mentioned in ROADMAP are implemented', () => {
      const roadmapContent = readFileSync(join(process.cwd(), 'ROADMAP.md'), 'utf-8');

      // Extract Git Integration section from v0.2.0
      const gitIntegrationSection = roadmapContent.match(/### Git Integration[\s\S]*?(?=###|---)/)?.[0];
      expect(gitIntegrationSection).toBeDefined();

      // Verify each claimed feature
      const claimedFeatures = [
        '🟢 Automatic PR creation via `gh` CLI',
        '🟢 PR description generation',
        '🟢 Commit message improvements'
      ];

      for (const feature of claimedFeatures) {
        expect(gitIntegrationSection).toContain(feature);
      }
    });

    it('should ensure ROADMAP status matches actual implementation completeness', () => {
      // This test ensures the ROADMAP accuracy for PR description generation

      // 1. Verify methods exist and work
      const orch = orchestrator as unknown as {
        generatePRTitle: Function;
        generatePRBody: Function;
      };

      expect(orch.generatePRTitle).toBeDefined();
      expect(orch.generatePRBody).toBeDefined();

      // 2. Verify they produce expected output format
      const testTask = {
        description: 'Test implementation',
        workflow: 'feature',
        id: 'test_id',
        branchName: 'apex/test',
        usage: { totalTokens: 1000, estimatedCost: 0.01 }
      };

      const title = orch.generatePRTitle(testTask);
      const body = orch.generatePRBody(testTask);

      expect(title).toMatch(/^feat:/);
      expect(body).toContain('## Summary');
      expect(body).toContain('## Task Details');

      // 3. Verify integration exists
      expect(orchestrator.createPullRequest).toBeDefined();

      // If we reach here without errors, the ROADMAP claim is accurate
      expect(true).toBe(true); // Explicit pass for this verification test
    });
  });
});