/**
 * Integration test suite for Zod Configuration Loading
 *
 * This test suite validates the integration between Zod schemas and configuration
 * loading functions. It tests real configuration file parsing, validation,
 * and error handling in realistic scenarios.
 *
 * @author Generated by QA Engineer - Testing Stage
 * @date 2026-02-28
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs/promises';
import * as path from 'path';
import * as yaml from 'yaml';
import {
  loadConfig,
  loadAgents,
  loadWorkflows,
  isApexInitialized,
  parseAgentMarkdown,
  getApexDir,
} from '../packages/core/src/config.js';
import {
  validateApexConfiguration,
  validateApexConfigFile,
  validateAgentDefinitions,
  validateWorkflowDefinitions,
} from '../packages/core/src/config-validation.js';
import { ApexConfigSchema, AgentDefinitionSchema, WorkflowDefinitionSchema } from '../packages/core/src/types.js';

describe('Zod Configuration Loading Integration', () => {
  const testProjectPath = '/tmp/apex-test-integration';
  const apexDir = path.join(testProjectPath, '.apex');

  beforeEach(async () => {
    // Clean up any existing test directory
    try {
      await fs.rm(testProjectPath, { recursive: true, force: true });
    } catch {
      // Ignore errors if directory doesn't exist
    }

    // Create test project directory structure
    await fs.mkdir(testProjectPath, { recursive: true });
    await fs.mkdir(apexDir, { recursive: true });
    await fs.mkdir(path.join(apexDir, 'agents'), { recursive: true });
    await fs.mkdir(path.join(apexDir, 'workflows'), { recursive: true });
    await fs.mkdir(path.join(apexDir, 'tools'), { recursive: true });

    // Change working directory to test project
    process.chdir(testProjectPath);
  });

  afterEach(async () => {
    // Restore original working directory
    process.chdir(__dirname);

    // Clean up test directory
    try {
      await fs.rm(testProjectPath, { recursive: true, force: true });
    } catch {
      // Ignore cleanup errors
    }
  });

  describe('Configuration File Loading and Validation', () => {
    it('should load and validate a complete APEX configuration', async () => {
      const configContent = {
        version: '1.0',
        project: {
          name: 'integration-test-project',
          description: 'Integration test for APEX configuration',
          version: '1.0.0'
        },
        autonomy: {
          level: 'review-before-commit'
        },
        agents: {
          enabled: ['planner', 'developer', 'tester'],
          disabled: ['experimental-agent']
        },
        models: {
          planning: 'opus',
          implementation: 'sonnet',
          review: 'haiku',
          default: 'sonnet'
        },
        git: {
          branchPrefix: 'apex/',
          commitFormat: 'conventional',
          autoCommit: false,
          autoPush: false
        },
        limits: {
          maxTokensPerTask: 500000,
          maxCostPerTask: 10.0,
          dailyBudget: 100.0,
          maxTurns: 100,
          maxConcurrentTasks: 3,
          maxRetries: 3
        },
        tools: {
          filesystem: {
            enabled: true,
            requireConfirmation: false,
            maxFileSize: 1048576, // 1MB
            allowedExtensions: ['.ts', '.js', '.json', '.md'],
            blockedExtensions: ['.exe', '.bat']
          },
          shell: {
            enabled: true,
            requireConfirmation: true,
            blockedCommands: ['rm -rf /', 'format', 'sudo'],
            allowElevatedPrivileges: false,
            environment: { NODE_ENV: 'development' }
          },
          web: {
            enabled: true,
            allowedDomains: ['api.openai.com', 'api.anthropic.com'],
            maxResponseSize: 5242880, // 5MB
            followRedirects: true
          },
          browser: {
            enabled: true,
            allowedDomains: ['localhost', 'test.example.com'],
            engine: 'chromium',
            backend: 'playwright',
            headless: true,
            viewport: { width: 1920, height: 1080 }
          }
        },
        mcp: {
          enabled: true,
          servers: [
            {
              name: 'filesystem',
              command: 'npx',
              args: ['@modelcontextprotocol/server-filesystem', './'],
              env: { NODE_ENV: 'production' }
            }
          ]
        }
      };

      // Write configuration to file
      const configPath = path.join(apexDir, 'config.yaml');
      await fs.writeFile(configPath, yaml.stringify(configContent));

      // Load and validate configuration
      const config = await loadConfig();
      expect(config).toBeDefined();

      // Verify Zod validation occurred during loading
      expect(() => ApexConfigSchema.parse(config)).not.toThrow();

      // Verify specific configuration values
      expect(config.project.name).toBe('integration-test-project');
      expect(config.autonomy?.level).toBe('review-before-commit');
      expect(config.models?.planning).toBe('opus');
      expect(config.limits?.maxTokensPerTask).toBe(500000);
      expect(config.tools?.filesystem?.maxFileSize).toBe(1048576);
      expect(config.mcp?.servers).toHaveLength(1);
    });

    it('should handle configuration loading with missing optional sections', async () => {
      const minimalConfigContent = {
        project: {
          name: 'minimal-project'
        }
      };

      const configPath = path.join(apexDir, 'config.yaml');
      await fs.writeFile(configPath, yaml.stringify(minimalConfigContent));

      const config = await loadConfig();
      expect(config).toBeDefined();
      expect(config.project.name).toBe('minimal-project');
      expect(config.version).toBe('1.0'); // Default from schema

      // Verify optional sections are properly undefined/defaulted
      expect(config.autonomy).toBeUndefined();
      expect(config.models).toBeUndefined();
      expect(config.tools).toBeUndefined();
    });

    it('should throw validation errors for invalid configuration', async () => {
      const invalidConfigContent = {
        project: {
          name: 123 // Invalid type - should be string
        },
        autonomy: {
          level: 'invalid-level' // Invalid enum value
        },
        models: {
          planning: 'gpt-4' // Invalid model name
        },
        limits: {
          maxTokensPerTask: -1, // Invalid negative value
          maxConcurrentTasks: 0 // Invalid zero value
        }
      };

      const configPath = path.join(apexDir, 'config.yaml');
      await fs.writeFile(configPath, yaml.stringify(invalidConfigContent));

      await expect(loadConfig()).rejects.toThrow();
    });

    it('should handle invalid YAML syntax', async () => {
      const invalidYamlContent = `
project:
  name: "test
  description: unclosed quote
  invalid: yaml: structure: [
`;

      const configPath = path.join(apexDir, 'config.yaml');
      await fs.writeFile(configPath, invalidYamlContent);

      await expect(loadConfig()).rejects.toThrow();
    });
  });

  describe('Agent Definition Loading and Validation', () => {
    it('should load and validate agent definitions from markdown files', async () => {
      const agentContent = `---
name: test-developer
description: A test development agent for integration testing
tools: Read,Write,Edit,Bash
model: sonnet
skills:
  - typescript
  - testing
  - debugging
prompt_version: 1.0
---

# Test Developer Agent

You are a skilled software developer specializing in TypeScript and testing.
Your role is to write, review, and improve code with a focus on quality and maintainability.

## Your Capabilities

- Write clean, well-documented TypeScript code
- Create comprehensive test suites
- Debug complex issues
- Follow best practices and coding standards

## Guidelines

- Always validate inputs and handle edge cases
- Write tests before implementing features (TDD)
- Use meaningful variable and function names
- Add JSDoc comments for public APIs
`;

      const agentPath = path.join(apexDir, 'agents', 'test-developer.md');
      await fs.writeFile(agentPath, agentContent);

      const agents = await loadAgents();
      expect(agents).toHaveLength(1);

      const agent = agents[0];
      expect(agent.name).toBe('test-developer');
      expect(agent.description).toBe('A test development agent for integration testing');
      expect(agent.model).toBe('sonnet');
      expect(agent.skills).toContain('typescript');

      // Verify Zod validation occurred
      expect(() => AgentDefinitionSchema.parse(agent)).not.toThrow();
    });

    it('should handle multiple agent files', async () => {
      const plannerAgent = `---
name: planner
description: Strategic planning agent
model: opus
tools: Read,Glob,Grep
---

You are a strategic planning agent.`;

      const developerAgent = `---
name: developer
description: Implementation agent
model: sonnet
tools: Read,Write,Edit,Bash,MultiEdit
---

You are a development agent.`;

      const testerAgent = `---
name: tester
description: Quality assurance agent
model: haiku
tools: Read,Bash,Grep
---

You are a testing agent.`;

      await fs.writeFile(path.join(apexDir, 'agents', 'planner.md'), plannerAgent);
      await fs.writeFile(path.join(apexDir, 'agents', 'developer.md'), developerAgent);
      await fs.writeFile(path.join(apexDir, 'agents', 'tester.md'), testerAgent);

      const agents = await loadAgents();
      expect(agents).toHaveLength(3);

      const agentNames = agents.map(a => a.name);
      expect(agentNames).toContain('planner');
      expect(agentNames).toContain('developer');
      expect(agentNames).toContain('tester');

      // Verify each agent validates
      agents.forEach(agent => {
        expect(() => AgentDefinitionSchema.parse(agent)).not.toThrow();
      });
    });

    it('should reject invalid agent definitions', async () => {
      const invalidAgentContent = `---
name: invalid-agent
description: ""
tools: InvalidTool,AnotherInvalidTool
model: gpt-4
---

`;

      const agentPath = path.join(apexDir, 'agents', 'invalid-agent.md');
      await fs.writeFile(agentPath, invalidAgentContent);

      await expect(loadAgents()).rejects.toThrow();
    });

    it('should handle missing frontmatter', async () => {
      const noFrontmatterContent = `
# Agent without frontmatter

This agent file is missing the required YAML frontmatter.
`;

      const agentPath = path.join(apexDir, 'agents', 'no-frontmatter.md');
      await fs.writeFile(agentPath, noFrontmatterContent);

      await expect(loadAgents()).rejects.toThrow();
    });

    it('should handle empty prompt content', async () => {
      const emptyPromptContent = `---
name: empty-prompt-agent
description: Agent with empty prompt
model: sonnet
---

`;

      const agentPath = path.join(apexDir, 'agents', 'empty-prompt.md');
      await fs.writeFile(agentPath, emptyPromptContent);

      await expect(loadAgents()).rejects.toThrow();
    });
  });

  describe('Workflow Definition Loading and Validation', () => {
    it('should load and validate workflow definitions', async () => {
      const workflowContent = {
        name: 'feature-development',
        description: 'Complete feature development workflow with comprehensive stages',
        stages: [
          {
            name: 'planning',
            agent: 'planner',
            description: 'Analyze requirements and create implementation plan'
          },
          {
            name: 'architecture',
            agent: 'architect',
            description: 'Design system architecture and data models'
          },
          {
            name: 'implementation',
            agent: 'developer',
            description: 'Implement the planned features'
          },
          {
            name: 'testing',
            agent: 'tester',
            description: 'Create and run comprehensive tests'
          },
          {
            name: 'review',
            agent: 'reviewer',
            description: 'Code review and quality assurance'
          }
        ]
      };

      const workflowPath = path.join(apexDir, 'workflows', 'feature-development.yaml');
      await fs.writeFile(workflowPath, yaml.stringify(workflowContent));

      const workflows = await loadWorkflows();
      expect(workflows).toHaveLength(1);

      const workflow = workflows[0];
      expect(workflow.name).toBe('feature-development');
      expect(workflow.stages).toHaveLength(5);
      expect(workflow.stages[0].name).toBe('planning');
      expect(workflow.stages[4].name).toBe('review');

      // Verify Zod validation occurred
      expect(() => WorkflowDefinitionSchema.parse(workflow)).not.toThrow();
    });

    it('should handle multiple workflow files', async () => {
      const quickWorkflow = {
        name: 'quick-fix',
        description: 'Quick bug fix workflow',
        stages: [
          { name: 'diagnosis', agent: 'developer', description: 'Identify the issue' },
          { name: 'fix', agent: 'developer', description: 'Implement the fix' },
          { name: 'verify', agent: 'tester', description: 'Verify the fix works' }
        ]
      };

      const fullWorkflow = {
        name: 'full-feature',
        description: 'Complete feature development',
        stages: [
          { name: 'planning', agent: 'planner', description: 'Plan the feature' },
          { name: 'implementation', agent: 'developer', description: 'Build the feature' },
          { name: 'testing', agent: 'tester', description: 'Test thoroughly' }
        ]
      };

      await fs.writeFile(path.join(apexDir, 'workflows', 'quick-fix.yaml'), yaml.stringify(quickWorkflow));
      await fs.writeFile(path.join(apexDir, 'workflows', 'full-feature.yaml'), yaml.stringify(fullWorkflow));

      const workflows = await loadWorkflows();
      expect(workflows).toHaveLength(2);

      const workflowNames = workflows.map(w => w.name);
      expect(workflowNames).toContain('quick-fix');
      expect(workflowNames).toContain('full-feature');
    });

    it('should reject workflows with empty stages', async () => {
      const emptyWorkflow = {
        name: 'empty-workflow',
        description: 'Workflow with no stages',
        stages: []
      };

      const workflowPath = path.join(apexDir, 'workflows', 'empty-workflow.yaml');
      await fs.writeFile(workflowPath, yaml.stringify(emptyWorkflow));

      await expect(loadWorkflows()).rejects.toThrow();
    });

    it('should reject workflows with invalid stage definitions', async () => {
      const invalidWorkflow = {
        name: 'invalid-workflow',
        description: 'Workflow with invalid stages',
        stages: [
          {
            // Missing required 'name' field
            agent: 'developer',
            description: 'Invalid stage'
          }
        ]
      };

      const workflowPath = path.join(apexDir, 'workflows', 'invalid-workflow.yaml');
      await fs.writeFile(workflowPath, yaml.stringify(invalidWorkflow));

      await expect(loadWorkflows()).rejects.toThrow();
    });
  });

  describe('Configuration Validation Integration', () => {
    it('should perform comprehensive validation of APEX project', async () => {
      // Set up a complete valid APEX project
      const configContent = {
        version: '1.0',
        project: { name: 'comprehensive-test-project' },
        autonomy: { level: 'review-before-commit' },
        models: { planning: 'opus', implementation: 'sonnet', review: 'haiku' },
        limits: { maxTokensPerTask: 500000, maxCostPerTask: 10.0, dailyBudget: 100.0 }
      };

      const agentContent = `---
name: test-agent
description: Test agent for validation
model: sonnet
---

You are a test agent.`;

      const workflowContent = {
        name: 'test-workflow',
        description: 'Test workflow',
        stages: [{ name: 'test', agent: 'test-agent', description: 'Test stage' }]
      };

      // Write all files
      await fs.writeFile(path.join(apexDir, 'config.yaml'), yaml.stringify(configContent));
      await fs.writeFile(path.join(apexDir, 'agents', 'test-agent.md'), agentContent);
      await fs.writeFile(path.join(apexDir, 'workflows', 'test-workflow.yaml'), yaml.stringify(workflowContent));

      const validationResult = await validateApexConfiguration();
      expect(validationResult.valid).toBe(true);
      expect(validationResult.summary.totalErrors).toBe(0);
      expect(validationResult.directory.valid).toBe(true);
      expect(validationResult.config.valid).toBe(true);
      expect(validationResult.agents.valid).toBe(true);
      expect(validationResult.workflows.valid).toBe(true);
    });

    it('should detect configuration validation errors', async () => {
      // Set up project with validation errors
      const invalidConfig = {
        project: { name: 123 }, // Invalid type
        autonomy: { level: 'invalid-level' }, // Invalid enum
        models: { planning: 'invalid-model' } // Invalid model
      };

      await fs.writeFile(path.join(apexDir, 'config.yaml'), yaml.stringify(invalidConfig));

      const validationResult = await validateApexConfiguration();
      expect(validationResult.valid).toBe(false);
      expect(validationResult.summary.totalErrors).toBeGreaterThan(0);
      expect(validationResult.config.valid).toBe(false);
    });

    it('should validate file existence and format', async () => {
      // Create incomplete APEX project (missing config file)
      const validationResult = await validateApexConfiguration();

      expect(validationResult.valid).toBe(false);
      expect(validationResult.config.errors.some(e =>
        e.type === 'missing_config_file'
      )).toBe(true);
    });
  });

  describe('Error Handling and Edge Cases', () => {
    it('should handle corrupted YAML files gracefully', async () => {
      const corruptedYaml = `
project:
  name: "test"
  description: "unclosed quote
autonomy:
  level: review-before-commit
  [invalid: structure
`;

      await fs.writeFile(path.join(apexDir, 'config.yaml'), corruptedYaml);

      await expect(loadConfig()).rejects.toThrow();
    });

    it('should handle permission errors', async () => {
      // Create config file with restricted permissions (Unix-like systems only)
      if (process.platform !== 'win32') {
        await fs.writeFile(path.join(apexDir, 'config.yaml'), 'project: { name: test }');
        await fs.chmod(path.join(apexDir, 'config.yaml'), 0o000); // No permissions

        await expect(loadConfig()).rejects.toThrow();

        // Restore permissions for cleanup
        await fs.chmod(path.join(apexDir, 'config.yaml'), 0o644);
      }
    });

    it('should handle very large configuration files', async () => {
      // Create large but valid configuration
      const largeConfig = {
        project: { name: 'large-project' },
        agents: {
          enabled: Array.from({ length: 1000 }, (_, i) => `agent-${i}`)
        },
        mcp: {
          enabled: true,
          servers: Array.from({ length: 100 }, (_, i) => ({
            name: `server-${i}`,
            command: 'node',
            args: [`script-${i}.js`],
            env: { ID: i.toString() }
          }))
        }
      };

      await fs.writeFile(path.join(apexDir, 'config.yaml'), yaml.stringify(largeConfig));

      const config = await loadConfig();
      expect(config.agents?.enabled).toHaveLength(1000);
      expect(config.mcp?.servers).toHaveLength(100);
    });

    it('should handle unicode and special characters in configuration', async () => {
      const unicodeConfig = {
        project: {
          name: '测试项目-🚀',
          description: 'Project with émojis and spëcial chars ñ ø å'
        }
      };

      await fs.writeFile(path.join(apexDir, 'config.yaml'), yaml.stringify(unicodeConfig));

      const config = await loadConfig();
      expect(config.project.name).toBe('测试项目-🚀');
    });
  });

  describe('Real-world Configuration Scenarios', () => {
    it('should handle enterprise-level configuration', async () => {
      const enterpriseConfig = {
        version: '1.0',
        project: {
          name: 'enterprise-application',
          description: 'Large-scale enterprise application',
          version: '2.1.0'
        },
        autonomy: {
          level: 'review-each-step'
        },
        agents: {
          enabled: ['architect', 'senior-developer', 'tester', 'security-reviewer'],
          disabled: ['experimental-ai', 'beta-agent']
        },
        models: {
          planning: 'opus',
          implementation: 'sonnet',
          review: 'sonnet',
          default: 'haiku'
        },
        git: {
          branchPrefix: 'feature/',
          commitFormat: 'conventional',
          autoCommit: false,
          autoPush: false
        },
        limits: {
          maxTokensPerTask: 1000000,
          maxCostPerTask: 50.0,
          dailyBudget: 500.0,
          maxTurns: 200,
          maxConcurrentTasks: 5,
          maxRetries: 5
        },
        tools: {
          filesystem: {
            enabled: true,
            requireConfirmation: true,
            maxFileSize: 10485760, // 10MB
            allowedExtensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '.md', '.yml', '.yaml'],
            blockedExtensions: ['.exe', '.bat', '.sh', '.ps1']
          },
          shell: {
            enabled: true,
            requireConfirmation: true,
            blockedCommands: ['rm -rf', 'sudo', 'chmod 777', 'format'],
            allowElevatedPrivileges: false
          },
          web: {
            enabled: true,
            allowedDomains: [
              'api.openai.com',
              'api.anthropic.com',
              'npmjs.com',
              'github.com'
            ],
            blockedDomains: ['malicious.com', 'unsafe.domain'],
            maxResponseSize: 52428800, // 50MB
            followRedirects: true
          }
        },
        permissions: {
          require_approval: ['shell', 'filesystem_write', 'web_access'],
          auto_approve: ['read', 'search']
        },
        mcp: {
          enabled: true,
          servers: [
            {
              name: 'database',
              command: 'python',
              args: ['-m', 'mcp_server_postgresql', '--connection', 'postgresql://localhost/db'],
              env: { PYTHONPATH: '/opt/mcp-servers' }
            },
            {
              name: 'monitoring',
              command: 'node',
              args: ['monitoring-server.js'],
              cwd: '/opt/monitoring',
              env: { NODE_ENV: 'production' }
            }
          ]
        }
      };

      await fs.writeFile(path.join(apexDir, 'config.yaml'), yaml.stringify(enterpriseConfig));

      const config = await loadConfig();
      expect(config).toBeDefined();
      expect(config.project.name).toBe('enterprise-application');
      expect(config.tools?.filesystem?.maxFileSize).toBe(10485760);
      expect(config.mcp?.servers).toHaveLength(2);

      // Verify this complex configuration validates properly
      expect(() => ApexConfigSchema.parse(config)).not.toThrow();
    });
  });
});