/**
 * Strategy Analyzer Interface and Types
 *
 * This module defines the common interface for all idle task strategy analyzers.
 * Each analyzer is responsible for analyzing project data and generating task
 * candidates for its specific strategy type (maintenance, refactoring, docs, tests).
 */

import { IdleTaskType, TaskPriority } from '@apexcli/core';
import type { ProjectAnalysis } from '../idle-processor';

/**
 * A candidate task generated by an analyzer.
 * Multiple candidates may be generated, and the analyzer will prioritize
 * them to select the best one.
 */
export interface TaskCandidate {
  /** Short title for the task */
  title: string;

  /** Detailed description of what needs to be done */
  description: string;

  /** Task priority based on impact and urgency */
  priority: TaskPriority;

  /** Estimated effort level */
  estimatedEffort: 'low' | 'medium' | 'high';

  /** Suggested workflow to use for this task */
  suggestedWorkflow: string;

  /** Explanation of why this task is valuable */
  rationale: string;

  /**
   * Score for prioritization within the analyzer (higher = more important).
   * This allows analyzers to rank multiple candidates from the same analysis.
   */
  score: number;

  /**
   * Unique identifier for deduplication across generation cycles.
   * Typically derived from the task's target (e.g., file path, dependency name).
   */
  candidateId: string;
}

/**
 * Interface for strategy analyzers.
 *
 * Each analyzer is responsible for:
 * 1. Analyzing project data relevant to its strategy type
 * 2. Generating task candidates based on identified issues
 * 3. Prioritizing candidates to select the most valuable one
 */
export interface StrategyAnalyzer {
  /** The strategy type this analyzer handles */
  readonly type: IdleTaskType;

  /**
   * Analyze project data and generate task candidates.
   *
   * @param analysis - The project analysis data from IdleProcessor
   * @returns Array of task candidates, may be empty if no issues found
   */
  analyze(analysis: ProjectAnalysis): TaskCandidate[];

  /**
   * Select the highest priority candidate from the list.
   *
   * @param candidates - Array of candidates to prioritize
   * @returns The best candidate, or null if no valid candidates
   */
  prioritize(candidates: TaskCandidate[]): TaskCandidate | null;
}

/**
 * Base class for strategy analyzers with common functionality.
 * Provides default prioritization logic that can be overridden.
 */
export abstract class BaseAnalyzer implements StrategyAnalyzer {
  abstract readonly type: IdleTaskType;

  abstract analyze(analysis: ProjectAnalysis): TaskCandidate[];

  /**
   * Default prioritization: select the candidate with the highest score.
   * Subclasses can override for more sophisticated prioritization.
   */
  prioritize(candidates: TaskCandidate[]): TaskCandidate | null {
    if (candidates.length === 0) {
      return null;
    }

    return candidates.reduce((best, current) =>
      current.score > best.score ? current : best
    );
  }

  /**
   * Helper to create a candidate with consistent structure.
   */
  protected createCandidate(
    id: string,
    title: string,
    description: string,
    options: {
      priority?: TaskPriority;
      effort?: 'low' | 'medium' | 'high';
      workflow?: string;
      rationale?: string;
      score?: number;
    } = {}
  ): TaskCandidate {
    return {
      candidateId: `${this.type}-${id}`,
      title,
      description,
      priority: options.priority ?? 'normal',
      estimatedEffort: options.effort ?? 'medium',
      suggestedWorkflow: options.workflow ?? this.type,
      rationale: options.rationale ?? `Identified during ${this.type} analysis`,
      score: options.score ?? 0.5,
    };
  }
}

// Re-export analyzer implementations
export { MaintenanceAnalyzer } from './maintenance-analyzer';
export { RefactoringAnalyzer } from './refactoring-analyzer';
export { DocsAnalyzer } from './docs-analyzer';
export { TestsAnalyzer } from './tests-analyzer';
export { VersionMismatchDetector } from './version-mismatch-detector';
